In [62]:
import pandas as pd
import numpy as np

In [63]:
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import OrdinalEncoder
from sklearn.model_selection import train_test_split

In [64]:
df = pd.read_csv('/content/covid_toy.csv')

In [65]:
df.head()

   age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [66]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [67]:
X_train,X_test,y_train,y_test=train_test_split(df.drop(columns=['has_covid']),df['has_covid'],test_size=0.2,random_state=0)

# **1. Aam Zindagi**

In [68]:
si = SimpleImputer()

X_train_fever=si.fit_transform(X_train[['fever']])
X_test_fever=si.fit_transform(X_test[['fever']])

X_train_fever.shape #as fever class had 10 missing values

(80, 1)

In [69]:
oe  = OrdinalEncoder(categories=[['Mild','Strong']],dtype=np.int32)

X_train_cough=oe.fit_transform(X_train[['cough']])
X_test_cough=oe.fit_transform(X_test[['cough']])

X_train_cough.shape

(80, 1)

In [70]:
ohe = OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32)

X_train_gender_city=ohe.fit_transform(X_train[['gender','city']])
X_test_gender_city=ohe.fit_transform(X_test[['gender','city']])

X_train_gender_city.shape

(80, 4)

In [71]:
X_train_age = X_train.drop(columns=['gender','fever','cough','city']).values
X_test_age = X_test.drop(columns=['gender','fever','cough','city']).values

X_train_age.shape

(80, 1)

In [72]:
X_train_transformed=np.concatenate((X_train_age,X_train_fever,X_train_gender_city,X_train_cough),axis=1)
X_test_transformed=np.concatenate((X_test_age,X_test_fever,X_test_gender_city,X_test_cough),axis=1)

X_train_transformed.shape

(80, 7)

# **2. Mentos Zindagi**

In [73]:
from sklearn.compose import ColumnTransformer

In [74]:
col = ColumnTransformer(transformers=[
    ('tnf1',SimpleImputer(),['fever']),
    ('tnf2',OrdinalEncoder(categories=[['Mild','Strong']],dtype=np.int32),['cough']),
    ('tnf3',OneHotEncoder(drop='first',sparse_output=False,dtype=np.int32),['gender','city'])
],remainder='passthrough')

In [75]:
X_train = col.fit_transform(X_train)
X_train.shape

(80, 7)