In [20]:
import numpy as np
import pandas as pd

In [21]:
date=pd.read_csv('/content/orders.csv')
time=pd.read_csv('/content/messages.csv')

In [23]:
date.head()

         date  product_id  city_id  orders
0  2019-12-10        5628       25       3
1  2018-08-15        3646       14     157
2  2018-10-23        1859       25       1
3  2019-08-17        7292       25       1
4  2019-01-06        4344       25       3

In [24]:
time.head()

                  date                                                msg
0  2013-12-15 00:50:00                           ищу на сегодня мужика 37
1  2014-04-29 23:40:00   ПАРЕНЬ БИ ИЩЕТ ДРУГА СЕЙЧАС!! СМС ММС 0955532826
2  2012-12-30 00:21:00           Днепр.м 43 позн.с д/ж *.о  067.16.34.576
3  2014-11-28 00:31:00  КИЕВ ИЩУ Д/Ж ДО 45 МНЕ СЕЙЧАС СКУЧНО 093 629 9...
4  2013-10-26 23:11:00    Зая я тебя никогда не обижу  люблю тебя!)  Даше

In [25]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   object
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: int64(3), object(1)
memory usage: 31.4+ KB

In [26]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

#  **Working With Dates**

In [27]:
date['date']=pd.to_datetime(date['date'])

In [28]:
date.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   date        1000 non-null   datetime64[ns]
 1   product_id  1000 non-null   int64
 2   city_id     1000 non-null   int64
 3   orders      1000 non-null   int64
dtypes: datetime64[ns](1), int64(3)
memory usage: 31.4 KB

## 1.Extract years

In [29]:
date['date_year']=date['date'].dt.year

date.head()

        date  product_id  city_id  orders  date_year
0 2019-12-10        5628       25       3       2019
1 2018-08-15        3646       14     157       2018
2 2018-10-23        1859       25       1       2018
3 2019-08-17        7292       25       1       2019
4 2019-01-06        4344       25       3       2019

## 2.Extract months

In [34]:
date['date_month']=date['date'].dt.month

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,<bound method PandasDelegate._add_delegate_acc...
1,2018-08-15,3646,14,157,2018,8,<bound method PandasDelegate._add_delegate_acc...
2,2018-10-23,1859,25,1,2018,10,<bound method PandasDelegate._add_delegate_acc...
3,2019-08-17,7292,25,1,2019,8,<bound method PandasDelegate._add_delegate_acc...
4,2019-01-06,4344,25,3,2019,1,<bound method PandasDelegate._add_delegate_acc...

## 3.Extract month name

In [36]:
date['date_month_name']=date['date'].dt.month_name()

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name
0,2019-12-10,5628,25,3,2019,12,December
1,2018-08-15,3646,14,157,2018,8,August
2,2018-10-23,1859,25,1,2018,10,October
3,2019-08-17,7292,25,1,2019,8,August
4,2019-01-06,4344,25,3,2019,1,January

## 4.Extract days

In [37]:
date['date_day']=date['date'].dt.day
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day
0,2019-12-10,5628,25,3,2019,12,December,10
1,2018-08-15,3646,14,157,2018,8,August,15
2,2018-10-23,1859,25,1,2018,10,October,23
3,2019-08-17,7292,25,1,2019,8,August,17
4,2019-01-06,4344,25,3,2019,1,January,6

## 4.Extract days name

In [38]:
date['date_day_name']=date['date'].dt.day_name()
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_name
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday

## 4.Extract days of week

In [41]:
date['date_day_of_week']=date['date'].dt.day_of_week


date.drop(columns=['product_id','city_id','orders'])
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_name,date_day_of_week
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6

In [43]:
# is Weekend

date['date_is_weekend']=np.where(date['date_day_name'].isin(['Sunday','Saturday']),1,0)

date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_name,date_day_of_week,date_is_weekend
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1,0
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2,0
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1,0
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5,1
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6,1

## Extract Week

In [48]:
date['date_week']=date['date'].dt.isocalendar().week
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_name,date_day_of_week,date_is_weekend,date_week
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1,0,50
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2,0,33
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1,0,43
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5,1,33
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6,1,1

## 6.Extract Quarter

In [49]:
date['date_quarter']=date['date'].dt.quarter
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_name,date_day_of_week,date_is_weekend,date_week,date_quarter
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1,0,50,4
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2,0,33,3
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1,0,43,4
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5,1,33,3
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6,1,1,1

## 7.Extract semester

In [51]:
date['date_semester']=np.where(date['date_quarter'].isin([1,2]),1,2)
date.head()

,date,product_id,city_id,orders,date_year,date_month,date_month_name,date_day,date_day_name,date_day_of_week,date_is_weekend,date_week,date_quarter,date_semester
0,2019-12-10,5628,25,3,2019,12,December,10,Tuesday,1,0,50,4,2
1,2018-08-15,3646,14,157,2018,8,August,15,Wednesday,2,0,33,3,2
2,2018-10-23,1859,25,1,2018,10,October,23,Tuesday,1,0,43,4,2
3,2019-08-17,7292,25,1,2019,8,August,17,Saturday,5,1,33,3,2
4,2019-01-06,4344,25,3,2019,1,January,6,Sunday,6,1,1,1,1

## Extract time between two dates

In [52]:
import datetime

today=datetime.datetime.today()

today

datetime.datetime(2026, 7, 9, 10, 17, 28, 89863)

In [53]:
today-date['date']

0     2403 days 10:17:28.089863
1     2885 days 10:17:28.089863
2     2816 days 10:17:28.089863
3     2518 days 10:17:28.089863
4     2741 days 10:17:28.089863
                 ...
995   2831 days 10:17:28.089863
996   2772 days 10:17:28.089863
997   2620 days 10:17:28.089863
998   2685 days 10:17:28.089863
999   2459 days 10:17:28.089863
Name: date, Length: 1000, dtype: timedelta64[ns]

In [54]:
(today-date['date']).dt.days

0      2403
1      2885
2      2816
3      2518
4      2741
       ...
995    2831
996    2772
997    2620
998    2685
999    2459
Name: date, Length: 1000, dtype: int64

In [57]:
#month passed

((today - date['date']).dt.days / 30).round()

0      80.0
1      96.0
2      94.0
3      84.0
4      91.0
       ...
995    94.0
996    92.0
997    87.0
998    90.0
999    82.0
Name: date, Length: 1000, dtype: float64

# **Working With Time**

In [58]:
time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   object
 1   msg     1000 non-null   object
dtypes: object(2)
memory usage: 15.8+ KB

In [60]:
time['date']=pd.to_datetime(time['date'])

time.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   date    1000 non-null   datetime64[ns]
 1   msg     1000 non-null   object
dtypes: datetime64[ns](1), object(1)
memory usage: 15.8+ KB

In [69]:
time['hours']=time['date'].dt.hour
time['min']=time['date'].dt.minute
time['sec']=time['date'].dt.second
time.head()

                 date  hours  min  sec
0 2013-12-15 00:50:00      0   50    0
1 2014-04-29 23:40:00     23   40    0
2 2012-12-30 00:21:00      0   21    0
3 2014-11-28 00:31:00      0   31    0
4 2013-10-26 23:11:00     23   11    0

In [71]:
time['time']=time['date'].dt.time
time.head()

                 date  hours  min  sec      time
0 2013-12-15 00:50:00      0   50    0  00:50:00
1 2014-04-29 23:40:00     23   40    0  23:40:00
2 2012-12-30 00:21:00      0   21    0  00:21:00
3 2014-11-28 00:31:00      0   31    0  00:31:00
4 2013-10-26 23:11:00     23   11    0  23:11:00

In [72]:
today-time['date']

0     4589 days 09:27:28.089863
1     4453 days 10:37:28.089863
2     4939 days 09:56:28.089863
3     4241 days 09:46:28.089863
4     4638 days 11:06:28.089863
                 ...
995   5228 days 09:27:28.089863
996   4549 days 11:03:28.089863
997   5014 days 10:40:28.089863
998   5130 days 10:43:28.089863
999   4402 days 10:52:28.089863
Name: date, Length: 1000, dtype: timedelta64[ns]

In [80]:
(today-time['date'])/np.timedelta64(1,'h')

0      110145.457803
1      106882.624469
2      118545.941136
3      101793.774469
4      111323.107803
           ...
995    125481.457803
996    109187.057803
997    120346.674469
998    123130.724469
999    105658.874469
Name: date, Length: 1000, dtype: float64