In [140]:
!pip install optuna

Requirement already satisfied: optuna in /usr/local/lib/python3.12/dist-packages (4.9.0)
Requirement already satisfied: alembic>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (1.19.1)
Requirement already satisfied: colorlog in /usr/local/lib/python3.12/dist-packages (from optuna) (6.12.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.2)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from optuna) (26.2)
Requirement already satisfied: sqlalchemy>=1.4.2 in /usr/local/lib/python3.12/dist-packages (from optuna) (2.0.51)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from optuna) (4.67.3)
Requirement already satisfied: PyYAML in /usr/local/lib/python3.12/dist-packages (from optuna) (6.0.3)
Requirement already satisfied: Mako in /usr/lib/python3/dist-packages (from alembic>=1.5.0->optuna) (1.1.3)
Requirement already satisfied: typing-extensions>=4.12 in /usr/local/lib/python3.12/dist-packages (from alembic>=1.5.0->optuna) (4.16.0)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy>=1.4.2->optuna) (3.5.3)

In [141]:
import optuna
from sklearn.datasets import load_diabetes
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [142]:
df = pd.read_csv('/content/diabetes.csv')

In [143]:
df.head()

   Pregnancies  Glucose  BloodPressure  ...  DiabetesPedigreeFunction  Age  Outcome
0            6      148             72  ...                     0.627   50        1
1            1       85             66  ...                     0.351   31        0
2            8      183             64  ...                     0.672   32        1
3            1       89             66  ...                     0.167   21        0
4            0      137             40  ...                     2.288   33        1

[5 rows x 9 columns]

In [144]:
import numpy as np

cols_with_missing_vals=['Glucose','BloodPressure','SkinThickness','Insulin','BMI']
df[cols_with_missing_vals]=df[cols_with_missing_vals].replace(0,np.nan)

df.fillna(df.median(),inplace=True)
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [145]:
X=df.drop('Outcome',axis=1)
y=df['Outcome']

X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.3,random_state=42)

scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [146]:
X_train.shape

(537, 8)

In [147]:
X_test.shape

(231, 8)

In [148]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

In [149]:
def objective(trial):
  n_estimators=trial.suggest_int('n_estimators',50,200)
  max_depth=trial.suggest_int('max_depth',1,20)

  model=RandomForestClassifier(
      n_estimators=n_estimators,
      max_depth=max_depth,
      random_state=42
  )

  score=cross_val_score(model,X_train,y_train,cv=3,scoring='accuracy').mean()
  return score

In [160]:
study=optuna.create_study(direction='maximize',sampler=optuna.samplers.GridSampler(search_space))
study.optimize(objective)

[I 2026-08-11 10:27:05,037] A new study created in memory with name: no-name-24beceac-5149-4271-aab6-344b82a6ec73
[I 2026-08-11 10:27:05,609] Trial 0 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 100, 'max_depth': 5}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-08-11 10:27:06,521] Trial 1 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 150, 'max_depth': 10}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-08-11 10:27:06,857] Trial 2 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 50, 'max_depth': 15}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-08-11 10:27:07,462] Trial 3 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 15}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-08-11 10:27:08,105] Trial 4 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 100, 'max_depth': 20}. Best is trial 0 with value: 0.7653631284916201.
[I 2026-08-11 10:27:08,412] Trial 5 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 10}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:09,272] Trial 6 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 150, 'max_depth': 5}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:10,210] Trial 7 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 150, 'max_depth': 20}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:11,152] Trial 8 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 150, 'max_depth': 15}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:14,852] Trial 9 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 200, 'max_depth': 10}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:16,999] Trial 10 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 200, 'max_depth': 20}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:18,654] Trial 11 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 200, 'max_depth': 15}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:19,808] Trial 12 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 200, 'max_depth': 5}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:20,122] Trial 13 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 50, 'max_depth': 5}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:20,776] Trial 14 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 100, 'max_depth': 10}. Best is trial 5 with value: 0.7746741154562384.
[I 2026-08-11 10:27:21,113] Trial 15 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 50, 'max_depth': 20}. Best is trial 5 with value: 0.7746741154562384.

In [161]:
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.RandomSampler())
study.optimize(objective,n_trials=50)

[I 2026-08-11 10:27:21,123] A new study created in memory with name: no-name-a45b87b8-497b-4b48-a72b-4847cbde8a74
[I 2026-08-11 10:27:22,060] Trial 0 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 145, 'max_depth': 8}. Best is trial 0 with value: 0.7597765363128492.
[I 2026-08-11 10:27:22,958] Trial 1 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 138, 'max_depth': 17}. Best is trial 1 with value: 0.7616387337057727.
[I 2026-08-11 10:27:23,706] Trial 2 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 115, 'max_depth': 14}. Best is trial 2 with value: 0.7672253258845437.
[I 2026-08-11 10:27:24,421] Trial 3 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 118, 'max_depth': 19}. Best is trial 2 with value: 0.7672253258845437.
[I 2026-08-11 10:27:25,696] Trial 4 finished with value: 0.7579143389199255 and parameters: {'n_estimators': 153, 'max_depth': 6}. Best is trial 2 with value: 0.7672253258845437.
[I 2026-08-11 10:27:26,229] Trial 5 finished with value: 0.7430167597765363 and parameters: {'n_estimators': 59, 'max_depth': 2}. Best is trial 2 with value: 0.7672253258845437.
[I 2026-08-11 10:27:27,505] Trial 6 finished with value: 0.7206703910614526 and parameters: {'n_estimators': 153, 'max_depth': 1}. Best is trial 2 with value: 0.7672253258845437.
[I 2026-08-11 10:27:28,067] Trial 7 finished with value: 0.7746741154562384 and parameters: {'n_estimators': 57, 'max_depth': 7}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:29,141] Trial 8 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 172, 'max_depth': 17}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:29,871] Trial 9 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 116, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:30,559] Trial 10 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 108, 'max_depth': 10}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:30,905] Trial 11 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 54, 'max_depth': 16}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:31,942] Trial 12 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 156, 'max_depth': 11}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:33,252] Trial 13 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 196, 'max_depth': 18}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:34,149] Trial 14 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 135, 'max_depth': 17}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:35,444] Trial 15 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 192, 'max_depth': 15}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:36,514] Trial 16 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 163, 'max_depth': 15}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:37,365] Trial 17 finished with value: 0.7541899441340781 and parameters: {'n_estimators': 124, 'max_depth': 20}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:37,783] Trial 18 finished with value: 0.7597765363128491 and parameters: {'n_estimators': 51, 'max_depth': 20}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:38,979] Trial 19 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 128, 'max_depth': 10}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:40,276] Trial 20 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 121, 'max_depth': 10}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:41,772] Trial 21 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 163, 'max_depth': 11}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:42,367] Trial 22 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 95, 'max_depth': 9}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:43,426] Trial 23 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 177, 'max_depth': 5}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:44,619] Trial 24 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 166, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:45,862] Trial 25 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 187, 'max_depth': 12}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:46,268] Trial 26 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 59, 'max_depth': 17}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:46,938] Trial 27 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 101, 'max_depth': 19}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:47,511] Trial 28 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 104, 'max_depth': 3}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:48,593] Trial 29 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 132, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:50,028] Trial 30 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 183, 'max_depth': 16}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:51,103] Trial 31 finished with value: 0.756052141527002 and parameters: {'n_estimators': 185, 'max_depth': 3}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:52,200] Trial 32 finished with value: 0.7541899441340781 and parameters: {'n_estimators': 109, 'max_depth': 20}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:52,954] Trial 33 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 68, 'max_depth': 8}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:54,826] Trial 34 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 199, 'max_depth': 4}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:55,209] Trial 35 finished with value: 0.7541899441340782 and parameters: {'n_estimators': 55, 'max_depth': 18}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:56,327] Trial 36 finished with value: 0.7728119180633147 and parameters: {'n_estimators': 178, 'max_depth': 16}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:56,969] Trial 37 finished with value: 0.7616387337057727 and parameters: {'n_estimators': 108, 'max_depth': 10}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:57,446] Trial 38 finished with value: 0.7523277467411545 and parameters: {'n_estimators': 74, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:58,403] Trial 39 finished with value: 0.756052141527002 and parameters: {'n_estimators': 186, 'max_depth': 3}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:27:59,207] Trial 40 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 133, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:00,394] Trial 41 finished with value: 0.7690875232774674 and parameters: {'n_estimators': 194, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:01,314] Trial 42 finished with value: 0.7597765363128492 and parameters: {'n_estimators': 145, 'max_depth': 8}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:02,236] Trial 43 finished with value: 0.7635009310986964 and parameters: {'n_estimators': 145, 'max_depth': 10}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:03,132] Trial 44 finished with value: 0.7672253258845437 and parameters: {'n_estimators': 148, 'max_depth': 9}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:03,985] Trial 45 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 135, 'max_depth': 9}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:04,810] Trial 46 finished with value: 0.7579143389199254 and parameters: {'n_estimators': 120, 'max_depth': 19}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:06,835] Trial 47 finished with value: 0.7709497206703911 and parameters: {'n_estimators': 198, 'max_depth': 16}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:08,335] Trial 48 finished with value: 0.7653631284916201 and parameters: {'n_estimators': 169, 'max_depth': 14}. Best is trial 7 with value: 0.7746741154562384.
[I 2026-08-11 10:28:08,993] Trial 49 finished with value: 0.7783985102420856 and parameters: {'n_estimators': 109, 'max_depth': 7}. Best is trial 49 with value: 0.7783985102420856.

In [162]:
print(f'best trial accuracy : {study.best_value}')
print(f'best hyperparameters : {study.best_params}')

best trial accuracy : 0.7783985102420856
best hyperparameters : {'n_estimators': 109, 'max_depth': 7}

In [163]:
from sklearn.metrics import accuracy_score

best_model=RandomForestClassifier(**study.best_params,random_state=42)

best_model.fit(X_train,y_train)

y_pred = best_model.predict(X_test)

test_accuracy=accuracy_score(y_test,y_pred)

print(f'Test Accuracy with best Parameter is :{test_accuracy}')

Test Accuracy with best Parameter is :0.7489177489177489

In [164]:
search_space = {
    'n_estimators':[50,100,150,200],
    'max_depth':[5,10,15,20]
}

In [165]:
from optuna.visualization import plot_optimization_history,plot_parallel_coordinate,plot_slice,plot_contour,plot_param_importances

In [166]:
plot_optimization_history(study)

In [167]:
plot_parallel_coordinate(study)

In [168]:
plot_slice(study)

In [169]:
plot_contour(study)

In [170]:
plot_param_importances(study)

In [171]:
from sklearn.ensemble import RandomForestClassifier,GradientBoostingClassifier
from sklearn.svm import SVC

In [172]:
def objective(trial):
    # Choose the algorithm to tune
    classifier_name = trial.suggest_categorical('classifier', ['SVM', 'RandomForest', 'GradientBoosting'])

    if classifier_name == 'SVM':
        # SVM hyperparameters
        c = trial.suggest_float('C', 0.1, 100, log=True)
        kernel = trial.suggest_categorical('kernel', ['linear', 'rbf', 'poly', 'sigmoid'])
        gamma = trial.suggest_categorical('gamma', ['scale', 'auto'])

        model = SVC(C=c, kernel=kernel, gamma=gamma, random_state=42)

    elif classifier_name == 'RandomForest':
        # Random Forest hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)
        bootstrap = trial.suggest_categorical('bootstrap', [True, False])

        model = RandomForestClassifier(
            n_estimators=n_estimators,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            bootstrap=bootstrap,
            random_state=42
        )

    elif classifier_name == 'GradientBoosting':
        # Gradient Boosting hyperparameters
        n_estimators = trial.suggest_int('n_estimators', 50, 300)
        learning_rate = trial.suggest_float('learning_rate', 0.01, 0.3, log=True)
        max_depth = trial.suggest_int('max_depth', 3, 20)
        min_samples_split = trial.suggest_int('min_samples_split', 2, 10)
        min_samples_leaf = trial.suggest_int('min_samples_leaf', 1, 10)

        model = GradientBoostingClassifier(
            n_estimators=n_estimators,
            learning_rate=learning_rate,
            max_depth=max_depth,
            min_samples_split=min_samples_split,
            min_samples_leaf=min_samples_leaf,
            random_state=42
        )

    # Perform cross-validation and return the mean accuracy
    score = cross_val_score(model, X_train, y_train, cv=3, scoring='accuracy').mean()
    return score

In [173]:
study = optuna.create_study(direction='maximize',sampler=optuna.samplers.TPESampler())
study.optimize(objective,n_trials=100)

[I 2026-08-11 10:38:49,062] A new study created in memory with name: no-name-a527b10f-b221-4974-9c0c-043a08255457
[I 2026-08-11 10:38:49,141] Trial 0 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.2603711137997444, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 0 with value: 0.7635009310986964.
[I 2026-08-11 10:38:50,462] Trial 1 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 166, 'max_depth': 19, 'min_samples_split': 9, 'min_samples_leaf': 7, 'bootstrap': False}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:38:51,707] Trial 2 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 91, 'max_depth': 16, 'min_samples_split': 2, 'min_samples_leaf': 8, 'bootstrap': True}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:38:51,761] Trial 3 finished with value: 0.7001862197392924 and parameters: {'classifier': 'SVM', 'C': 5.119072763868795, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:38:53,271] Trial 4 finished with value: 0.7765363128491619 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 64, 'learning_rate': 0.022632530037109893, 'max_depth': 17, 'min_samples_split': 10, 'min_samples_leaf': 8}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:38:55,897] Trial 5 finished with value: 0.7337057728119181 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 152, 'learning_rate': 0.08778465578879462, 'max_depth': 14, 'min_samples_split': 3, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:38:55,958] Trial 6 finished with value: 0.7579143389199255 and parameters: {'classifier': 'SVM', 'C': 11.377557343297397, 'kernel': 'rbf', 'gamma': 'auto'}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:38:57,593] Trial 7 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 87, 'learning_rate': 0.17733238193643436, 'max_depth': 14, 'min_samples_split': 8, 'min_samples_leaf': 10}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:39:01,266] Trial 8 finished with value: 0.750465549348231 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 290, 'learning_rate': 0.042134798468916, 'max_depth': 9, 'min_samples_split': 6, 'min_samples_leaf': 10}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:39:04,887] Trial 9 finished with value: 0.7616387337057727 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 239, 'learning_rate': 0.010174778081072733, 'max_depth': 12, 'min_samples_split': 10, 'min_samples_leaf': 6}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:39:05,605] Trial 10 finished with value: 0.7523277467411545 and parameters: {'classifier': 'RandomForest', 'n_estimators': 175, 'max_depth': 3, 'min_samples_split': 5, 'min_samples_leaf': 1, 'bootstrap': False}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:39:05,906] Trial 11 finished with value: 0.7616387337057727 and parameters: {'classifier': 'RandomForest', 'n_estimators': 57, 'max_depth': 20, 'min_samples_split': 10, 'min_samples_leaf': 6, 'bootstrap': False}. Best is trial 1 with value: 0.7765363128491621.
[I 2026-08-11 10:39:06,633] Trial 12 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 157, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 12 with value: 0.7783985102420856.
[I 2026-08-11 10:39:07,424] Trial 13 finished with value: 0.7690875232774674 and parameters: {'classifier': 'RandomForest', 'n_estimators': 159, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 12 with value: 0.7783985102420856.
[I 2026-08-11 10:39:08,344] Trial 14 finished with value: 0.7783985102420856 and parameters: {'classifier': 'RandomForest', 'n_estimators': 198, 'max_depth': 20, 'min_samples_split': 8, 'min_samples_leaf': 8, 'bootstrap': False}. Best is trial 12 with value: 0.7783985102420856.
[I 2026-08-11 10:39:09,467] Trial 15 finished with value: 0.7802607076350093 and parameters: {'classifier': 'RandomForest', 'n_estimators': 211, 'max_depth': 17, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-08-11 10:39:11,486] Trial 16 finished with value: 0.7597765363128491 and parameters: {'classifier': 'RandomForest', 'n_estimators': 229, 'max_depth': 17, 'min_samples_split': 6, 'min_samples_leaf': 10, 'bootstrap': True}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-08-11 10:39:12,396] Trial 17 finished with value: 0.7709497206703911 and parameters: {'classifier': 'RandomForest', 'n_estimators': 124, 'max_depth': 10, 'min_samples_split': 6, 'min_samples_leaf': 4, 'bootstrap': False}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-08-11 10:39:13,396] Trial 18 finished with value: 0.7765363128491621 and parameters: {'classifier': 'RandomForest', 'n_estimators': 219, 'max_depth': 15, 'min_samples_split': 7, 'min_samples_leaf': 9, 'bootstrap': False}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-08-11 10:39:14,978] Trial 19 finished with value: 0.7672253258845437 and parameters: {'classifier': 'RandomForest', 'n_estimators': 290, 'max_depth': 18, 'min_samples_split': 5, 'min_samples_leaf': 4, 'bootstrap': True}. Best is trial 15 with value: 0.7802607076350093.
[I 2026-08-11 10:39:15,011] Trial 20 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.14639387146476918, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7821229050279329.
[I 2026-08-11 10:39:15,042] Trial 21 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.1324470459013151, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 20 with value: 0.7821229050279329.
[I 2026-08-11 10:39:15,075] Trial 22 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.15453048452436108, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 22 with value: 0.7839851024208566.
[I 2026-08-11 10:39:15,106] Trial 23 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10720085704542717, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,138] Trial 24 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10859857799845984, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,171] Trial 25 finished with value: 0.7765363128491621 and parameters: {'classifier': 'SVM', 'C': 0.4785090518883521, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,210] Trial 26 finished with value: 0.7337057728119181 and parameters: {'classifier': 'SVM', 'C': 0.7728776915109913, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,253] Trial 27 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.10175289288050966, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,296] Trial 28 finished with value: 0.7709497206703911 and parameters: {'classifier': 'SVM', 'C': 1.063294109386747, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,652] Trial 29 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 92.97851091031201, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,684] Trial 30 finished with value: 0.7783985102420856 and parameters: {'classifier': 'SVM', 'C': 0.3241336395761799, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,715] Trial 31 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.11117802787170478, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,745] Trial 32 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10319628077563969, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,777] Trial 33 finished with value: 0.7802607076350093 and parameters: {'classifier': 'SVM', 'C': 0.27898309857373527, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,817] Trial 34 finished with value: 0.707635009310987 and parameters: {'classifier': 'SVM', 'C': 0.10288185895494967, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,851] Trial 35 finished with value: 0.7225325884543761 and parameters: {'classifier': 'SVM', 'C': 0.2629077414851984, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,884] Trial 36 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.2132014854782887, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,919] Trial 37 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.7107539740724372, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,954] Trial 38 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.19325111828444144, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:15,995] Trial 39 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 1.647217716504363, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:16,864] Trial 40 finished with value: 0.7392923649906891 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 109, 'learning_rate': 0.2517002802522716, 'max_depth': 4, 'min_samples_split': 3, 'min_samples_leaf': 1}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:16,896] Trial 41 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10477922145528304, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:16,928] Trial 42 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10793019593787138, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:16,958] Trial 43 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1027912604606063, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:16,990] Trial 44 finished with value: 0.7765363128491621 and parameters: {'classifier': 'SVM', 'C': 0.37944322352320214, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:17,023] Trial 45 finished with value: 0.7206703910614524 and parameters: {'classifier': 'SVM', 'C': 0.19051350574159953, 'kernel': 'poly', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:20,248] Trial 46 finished with value: 0.7467411545623835 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 273, 'learning_rate': 0.0601546168188075, 'max_depth': 6, 'min_samples_split': 4, 'min_samples_leaf': 2}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:20,293] Trial 47 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 0.17982149569218123, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:20,331] Trial 48 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.4446690324094391, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:20,363] Trial 49 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.10081849486439907, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:22,832] Trial 50 finished with value: 0.7318435754189944 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 131, 'learning_rate': 0.01001244221390328, 'max_depth': 8, 'min_samples_split': 2, 'min_samples_leaf': 3}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:22,881] Trial 51 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.15103850234055635, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:22,926] Trial 52 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.1034758260311838, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:22,988] Trial 53 finished with value: 0.7635009310986964 and parameters: {'classifier': 'SVM', 'C': 0.23335081076815123, 'kernel': 'sigmoid', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:23,034] Trial 54 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.17090386813335706, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:23,079] Trial 55 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10232083718279815, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:23,143] Trial 56 finished with value: 0.7672253258845437 and parameters: {'classifier': 'SVM', 'C': 0.15661569589664182, 'kernel': 'sigmoid', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:23,194] Trial 57 finished with value: 0.7802607076350093 and parameters: {'classifier': 'SVM', 'C': 0.2625067571265371, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:23,259] Trial 58 finished with value: 0.750465549348231 and parameters: {'classifier': 'SVM', 'C': 0.14568677569734753, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,181] Trial 59 finished with value: 0.7411545623836128 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 254, 'learning_rate': 0.11631189451757201, 'max_depth': 12, 'min_samples_split': 4, 'min_samples_leaf': 5}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,217] Trial 60 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.14960869447731145, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,249] Trial 61 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10398338527212579, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,281] Trial 62 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.14269610862590695, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,313] Trial 63 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.13430491067794542, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,347] Trial 64 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.21711641235454987, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,378] Trial 65 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.1017278977287767, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,445] Trial 66 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 5.785936574391032, 'kernel': 'linear', 'gamma': 'auto'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:28,482] Trial 67 finished with value: 0.7262569832402234 and parameters: {'classifier': 'SVM', 'C': 0.32066983666151705, 'kernel': 'poly', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:29,541] Trial 68 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 184, 'max_depth': 6, 'min_samples_split': 9, 'min_samples_leaf': 2, 'bootstrap': True}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:29,576] Trial 69 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.13458885092950035, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:29,611] Trial 70 finished with value: 0.7839851024208566 and parameters: {'classifier': 'SVM', 'C': 0.20107666941143212, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:29,643] Trial 71 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10256008674452209, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:30,003] Trial 72 finished with value: 0.7746741154562384 and parameters: {'classifier': 'SVM', 'C': 86.90432170493628, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:30,039] Trial 73 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.12494664830753296, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:30,072] Trial 74 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.12710630184009467, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:30,105] Trial 75 finished with value: 0.7858472998137803 and parameters: {'classifier': 'SVM', 'C': 0.10242884979186917, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:30,140] Trial 76 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.18436993125941287, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:31,665] Trial 77 finished with value: 0.7653631284916201 and parameters: {'classifier': 'RandomForest', 'n_estimators': 261, 'max_depth': 11, 'min_samples_split': 3, 'min_samples_leaf': 3, 'bootstrap': True}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:31,705] Trial 78 finished with value: 0.7728119180633147 and parameters: {'classifier': 'SVM', 'C': 0.2683744577757287, 'kernel': 'rbf', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:33,907] Trial 79 finished with value: 0.7653631284916201 and parameters: {'classifier': 'GradientBoosting', 'n_estimators': 197, 'learning_rate': 0.021752068779392474, 'max_depth': 6, 'min_samples_split': 5, 'min_samples_leaf': 5}. Best is trial 23 with value: 0.7858472998137803.
[I 2026-08-11 10:39:33,940] Trial 80 finished with value: 0.7821229050279329 and parameters: {'classifier': 'SVM', 'C': 0.12905523798875845, 'kernel': 'linear', 'gamma': 'scale'}. Best is trial 23 with value: 0.7858472998137803.

In [174]:
study.best_params

{'classifier': 'SVM',
 'C': 0.10720085704542717,
 'kernel': 'linear',
 'gamma': 'scale'}

In [175]:
study.best_value

0.7858472998137803

In [176]:
study.trials_dataframe()

    number     value  ... params_n_estimators     state
0        0  0.763501  ...                 NaN  COMPLETE
1        1  0.776536  ...               166.0  COMPLETE
2        2  0.765363  ...                91.0  COMPLETE
3        3  0.700186  ...                 NaN  COMPLETE
4        4  0.776536  ...                64.0  COMPLETE
..     ...       ...  ...                 ...       ...
95      95  0.765363  ...               136.0  COMPLETE
96      96  0.783985  ...                 NaN  COMPLETE
97      97  0.752328  ...                80.0  COMPLETE
98      98  0.754190  ...                 NaN  COMPLETE
99      99  0.782123  ...                 NaN  COMPLETE

[100 rows x 16 columns]

In [180]:
study.trials_dataframe()['params_classifier'].value_counts()

params_classifier
SVM                 74
RandomForest        15
GradientBoosting    11
Name: count, dtype: int64

In [181]:
study.trials_dataframe().groupby('params_classifier')['value'].mean()

params_classifier
GradientBoosting    0.751143
RandomForest        0.767970
SVM                 0.773567
Name: value, dtype: float64

In [182]:
plot_optimization_history(study).show()

In [183]:
plot_slice(study).show()